### ISSUE TITLE
Transforming NETCDF file to Relational Databases

### ISSUE THREAD

**Issue by litethesko** [MetOffice/aws-earth-examples#10]
Hi, I am in a process to convert the MET Office Cube Data which is in NETCDF format to relational world for reporting and dashboards. Do you know how can i do that?

**Comment by jwovens** [comment]
Hi @litethesko .  When I hear "relational world", I normally assume people want to load the data in to a relational database.  Is this what you're trying to do?  I assume you've seen the getting started page at [getting started page](https://github.com/MetOffice/aws-earth-examples/blob/master/examples/1.%20Getting%20Started.ipynb) which advocates using the Python iris package to read the data in to memory.  There are other tools available at the [unidata website](https://www.unidata.ucar.edu/downloads/index.jsp).

**Comment by armeniopinto** [comment]
Hello @litethesko ! Can you provide us more details about your set-up? What database are you using?
