### ISSUE TITLE
Data info link in Open Data description unavailable

### ISSUE THREAD

**Issue by tom98784** [MetOffice/aws-earth-examples#11]
In the description of the dataset on AWS Open Data [here](https://registry.opendata.aws/uk-met-office/), it says 'For information about the data see the Met Office website', and links to https://www.metoffice.gov.uk/services/data-provision/big-data-drive/wholesale/categories/planetary-scale-applications

Attempting to follow the link, I get a 'page not found' error.

**Comment by armeniopinto** [comment]
Hello Tom, thank you for spotting that, we'll fix it soon!

**Comment by ZH-MO** [comment]
Hi I've fixed it earlier, just realised Tom posted it. So the link works now.
