### ISSUE TITLE
List the version of Iris module in Example/1. Getting Started

### ISSUE THREAD

**Issue by LanceNero** [MetOffice/aws-earth-examples#12]
some APIs has deprecated in Iris latest version, such as:
![image](https://user-images.githubusercontent.com/2245754/61735611-e76f6080-adb6-11e9-9182-dd5eab445c54.png)

List the Iris version used in the example.

Regards!

**Comment by tom98784** [comment]
I can run the `1. Getting Started` notebook without issue using Iris 2.2.1dev0.
Could you add which version of Iris you're using and what section of the notebook you're running when you get these errors?
Looking at the documentation, it seems that coord is an attribute of Cube but not CubeList.
