### ISSUE TITLE
Historic Data

### ISSUE THREAD

**Issue by maewart** [MetOffice/aws-earth-examples#16]
Hi, I would like to get the SNS messages for historic data.

The example provided is only to get newly available data, however I am looking for data in 2018.

I can see the list of files in: https://s3.eu-west-2.amazonaws.com/aws-earth-mo-atmospheric-ukv-prd so can make some intelligent guesses, however it would be ideal if I can get the SNS Message data for them.

Any help greatly appreciated.

Thanks,

Martin

**Comment by maewart** [comment]
Actually, just to add to this, I can't find any data back in 2018 this way. I'd need to be able to get the SNS messages for 2018.

**Comment by TomDufall** [comment]
Hi Martin,

This project only provides a rolling window of data - it's automatically deleted after 1-5 days (can't remember the exact timescale off the top of my head.)
