### ISSUE TITLE
UKV Deterministic service stopped

### ISSUE THREAD

**Issue by fepeacock** [MetOffice/aws-earth-examples#18]
Hello,

The UKV Deterministic model output has stopped around midnight today. Could you please advise?

Many thanks,

Frank

**Comment by TomDufall** [comment]
Hi Frank,

I don't have any exact details, but I believe there was recently some disruption to the generation and/or processing of UKV. This was the night before last, so would explain some disruption to this data feed last night (24h delay.) Let me know if any issues continue.

Tom

**Comment by fepeacock** [comment]
Hello Tom,

Many thanks for your quick reply. The files have back-filled and all is 
back to normal.

Thanks,

Frank

**Comment by armeniopinto** [comment]
Frank, thank you for letting us know about this. Regards, Arménio
