### ISSUE TITLE
Cannot access data in MOGREPS-UK S3 bucket

### ISSUE THREAD

**Issue by KatherineTomkins** [MetOffice/aws-earth-examples#2]
Hi,
Believe it allows public access, I am able to list the bucket, but unable
to retrieve files from it:
aws-earth-mo-atmospheric-mogreps-uk-prd

Command:
aws s3 cp s3://aws-earth-mo-atmospheric-mogreps-uk-prd/
8732490bb7e5a710eea5ff25830aaad8a48c57cc.nc sample.nc
Got:
"fatal error: An error occurred (403) when calling the HeadObject
operation: Forbidden"

I know it is holiday season, appreciate your help!

Thanks,
Yiqun

**Comment by armeniopinto** [comment]
I can confirm the same problem. It's definitely a permissions problem, @jacobtomlinson, is this something you can fix?

**Comment by jacobtomlinson** [comment]
Thanks for raising this. I don't seem to be able to reproduce this with my IAM user. 

The bucket has [public permissions](https://gist.github.com/jacobtomlinson/760b998c2a75c8c2e5f5ff5e0a65b933), so perhaps the IAM user you are using also needs permissions.

My user account has full S3 read permissions. Perhaps your IAM user needs to be given permission to read from S3?

**Comment by jacobtomlinson** [comment]
Looks like this is an issue with S3. There seems to be a bug with applying the permissions correctly due to the way we are writing the files. I'm looking at implementing a fix now.

**Comment by TheBadEye** [comment]
As of right now I can confirm the following Illicits a:
"errorMessage": "An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied"

Exception when the following code is executed in LAMDA:
[s3.Object("MY_TEST_BUCKET", "e6434c6f83a5af5fbd108beb048be7cb8335e9c6.nc").copy_from(CopySource = {'Bucket': "aws-earth-mo-atmospheric-ukv-prd", 'Key': "e6434c6f83a5af5fbd108beb048be7cb8335e9c6.nc"})](url)

The target is confirmed as being there via SNS Topic QUEUE

**Comment by jacobtomlinson** [comment]
This is now resolved. Any new files created going forwards will have correct permissions. Apologies for the inconvenience.

**Comment by armeniopinto** [comment]
> As of right now I can confirm the following Illicits a:
> "errorMessage": "An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied"

Hello @TheBadEye ! Everything should be working now, let us know if you're still having issues!
