### ISSUE TITLE
Insufficient descriptive information in messages on UK Deterministic 

### ISSUE THREAD

**Issue by fepeacock70** [MetOffice/aws-earth-examples#4]

**Comment by armeniopinto** [comment]
Hello @fepeacock70 ! Did you manage to fix the problem you were having?

**Comment by fepeacock70** [comment]
Armenio: I am still experimenting on learning the details of the message 
contents. I will reply with full details later. Thanks.

**Comment by fepeacock70** [comment]
Hello Armenio,

I have continued with the receipt of messages for the UKMO UK 
Deterministic 2km model. I have understood what an AWS request on the 
SQS service is. At present I am accumulating approximately ~150,000 
requests per day. This is a result of sending, receiving and deleting 
~50,000 messages a day. Is there not a better more efficient means of 
subscribing to a subset of the UK Deterministic model such as for 
specific variables or cycles of the day?

Thanks,

Frank

**Comment by fepeacock70** [comment]
Hello,

Has the UKMO 2km Deterministic model output on AWS service expired?

It appears that I am no longer receiving messages. I have been 
subscribed since January 2019.

Thanks,

Frank

**Comment by TomDufall** [comment]
Hi Frank,

There has been an issue with our system which I was alerted to yesterday. I completed the fix for it this morning, but it'll be 24h before data starts being released again. You should start seeing data from approx 10:30 tomorrow.

Kind regards,
Tom

**Comment by TomDufall** [comment]
For future reference, it's more visible to everyone if you open a new issue for a separate problem rather than replying on an old one.
