### ISSUE TITLE
Working out valid URLs

### ISSUE THREAD

**Issue by philip-brohan** [MetOffice/aws-earth-examples#5]
I'm trying to get MOGREPS-G data.

From https://registry.opendata.aws/uk-met-office/, I think the bucket is:

https://s3.eu-west-2.amazonaws.com/aws-earth-mo-atmospheric-mogreps-g-prd/

From https://www.metoffice.gov.uk/binaries/content/assets/mohippo/pdf/data-provision/mogreps-uk-ensemble-beta-service-parameters-080818.pdf I know the file name pattern for the MSLP is:

[YYYYMMDD]T[hhmm]Z-PT[nnnn]H[mm]M- pressure_at_mean_sea_level.nc 

I'm assuming [YYYYMMDD]T[hhmm] is the date of the run and that's given at https://www.metoffice.gov.uk/services/data-provision/big-data-drive/wholesale/categories/planetary-scale-applications - within the last 7 days so 

20190110T0000

I'm guessing that [nnnn] is the number of hours ahead the forecast is. I choose '0006'

I'm guessing that [mm] is the number of minutes ahead the forecast is - so always '00'

So my URL is

https://s3.eu-west-2.amazonaws.com/aws-earth-mo-atmospheric-mogreps-g-prd/20190110T0000Z-PT006H00M-pressure_at_mean_sea_level.nc 

But this URL does not exist (404s). What am I doing wrong, please, and what documentation have I not read.

**Comment by jacobtomlinson** [comment]
Thanks for raising this @philip-brohan. I've just had a look and currently the files are not following the naming convention you are linking to. Due to the way things are fed out of the internal Met Office systems I think this information is being lost and the filename is being set to a hash of the NetCDF metadata. Which isn't very useful. 

Currently the only way to get data is by consuming object creation notifications as per the documentation. I'll start investigating a fix now.

**Comment by armeniopinto** [comment]
Hey @philip-brohan , thank you! We will update the documentation to reflect the fact that the file names are obfuscated. The reason is that we don't want users to depend on the file names structure, as it will eventually change and break their code. We prefer users to depend on the metadata in the SNS message instead.

**Comment by philip-brohan** [comment]
Can I urge you to think again about this? It seems perverse to deliberately disable the simplest and lowest-tech data access method.

I'm tempted to offer you a bet that it will be necessary to make a code-breaking change in the SNS service (many moving parts) long before the filenames need changing. But my problem is more fundamental. I don't use the AWS infrastructure; I have no access to SNS.

 So though I'd love to use your data, I'm going to stick with ECMWF products and Copernicus. Thanks for trying.

**Comment by armeniopinto** [comment]
> But my problem is more fundamental. I don't use the AWS infrastructure; I have no access to SNS.

Hello @philip-brohan ! You don't need to use AWS to be a client of SNS. You don't even need to use any of their helper libraries (although they are quite handy, and support all common languages).

Our documentation example focuses on piping the messages to SQS, as it's simpler. But you can use the HTTP endpoint mechanism to do the same; here is a [short Python example](https://gist.github.com/iMilnb/bf27da3f38272a76c801) of how that works.

I do understand and accept your remark about having a lightweight way to reference this data. This is a community project hosted by the Met Office in collaboration with AWS, and one of our goals is to understand how our users want to interact with the data. If we need a better way to reference the data, then we will build it, and we would be more than happy to have you on-board, an extra pair of hands is great!

**Comment by philip-brohan** [comment]
> You don't need to use AWS to be a client of SNS.

I did not know that, thank you. I'll look into using that approach to build a calalogue to de-obfuscate the file names.

**Comment by armeniopinto** [comment]
Perfect! If this is something you are willing to share, it would be really cool to understand your approach, as we also have an objective to create a metadata catalogue for ad hoc retrieval of data! Don't hesitate to get in touch back here if you find any issues, there's always someone around to help ;).
